add functionality for setting picture settings
Drafteed/pybravia pull request #21
Opened 2023-03-02 02:19 UTC by NickBorgers

I want to allow my home automation to manipulate the brightness of my TV in sync with the lighting of the home. I need this module to allow me to interact with that configuration of the TV, which this PR adds.

I will then attempt to follow-up and add the ability for Home Assistant to leverage this functionality.

2023-03-02 02:19 UTC, NickBorgers commented on README.md
> +import asyncio
Changes to the README are simply to make this example runnable. I couldn't run the current form because the async wasn't being applied to a function.

2023-03-02 02:20 UTC, NickBorgers commented on pybravia/client.py
> +    async def set_picture_setting(self, target: str, value: str | None = None) -> bool:
Tested lightly, plainly based on docs here: https://pro-bravia.sony.net/develop/integrate/rest-api/spec/service/video/v1_0/setPictureQualitySettings/index.html

2023-03-02 02:20 UTC, NickBorgers commented on pybravia/client.py
> +    async def get_picture_setting_full(self) -> list[dict[str, Any]]:
I tested lightly, used documentation here: https://pro-bravia.sony.net/develop/integrate/rest-api/spec/service/video/v1_0/getPictureQualitySettings/index.html

2023-03-02 13:58 UTC, Drafteed requested changes

2023-03-02 13:58 UTC, Drafteed commented on pybravia/client.py
> +        return result
```suggestion
    async def get_picture_setting(self, target: str = "") -> list[dict[str, Any]]:
        """Get information about the picture settings."""
        resp = await self.send_rest_req(SERVICE_VIDEO, "getPictureQualitySettings", {"target": target})
        result = resp.get("result", [[]])[0]
        return result
```

2023-03-02 13:58 UTC, Drafteed commented on README.md
> +import asyncio
Let's take this to a separate PR. Other examples also need to be corrected.

2023-03-02 13:58 UTC, Drafteed commented on pybravia/client.py
> +            {"settings": [{"target": target, "value": str(value)}]},
```suggestion
            {"settings": [{"target": target, "value": value}]},
```

2023-03-02 13:58 UTC, Drafteed commented on pybravia/client.py
> +    async def set_picture_setting(self, target: str, value: str | None = None) -> bool:
`value` must only be a `string`.
```suggestion
    async def set_picture_setting(self, target: str, value: str) -> bool:
```

2023-03-03 08:24 UTC, Drafteed commented on pybravia/client.py
> +        resp = await self.send_rest_req(SERVICE_VIDEO, "getPictureQualitySettings", {"target": target})
```suggestion
        resp = await self.send_rest_req(
            SERVICE_VIDEO, "getPictureQualitySettings", {"target": target}
        )
```

2023-03-03 08:31 UTC, Drafteed approved these changes
Looks good! Thanks!

2023-03-03 08:31 UTC, merged

2023-03-03 09:38 UTC, Drafteed commented
I've created a new release (v0.3.2) which contains your change.